name: End-to-end tests

on:
  push:
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-18.04    # tested on: 18.04/20.04
    steps:
      - uses: actions/checkout@v1
      - uses: jonaseberle/github-action-setup-ddev@v1
      # composer install
      - run: ddev composer install
      # create basic environment
      - run: ddev exec "cat .env.example | sed  -E 's/DB_(HOST|DATABASE|USERNAME|PASSWORD)=(.*)/DB_\1=db/g' > .env"
      # Generate key
      - run: ddev exec "php artisan key:generate"
      # Generate key
      - run: ddev cypress-run
